### ISSUE TITLE
Video encryption

### ISSUE THREAD

**Issue by syatoralbert** [benoitsan/BBAES#2]
I have been using this library for my file encryption in Swift. I have encrypted pdf file and managed to display the decrypted pdf file. However, when I run the codes using .mp4 format file, the file cannot be play in the video player. I suspect that the decrypted file produced is not the same file as the original so that the decrypted file remain as a meaningless file. May I know why is this happening?

**Comment by benoitsan** [comment]
I'm sorry but I don't have the time to get into this.
