### ISSUE TITLE
Decryption Returns null 

### ISSUE THREAD

**Issue by Gantaios** [benoitsan/BBAES#3]
NSData *dec = [BBAES decryptedDataFromData:receievedData IV:ivData key:symKey];
    NSLog(@"dec is %@",dec);
 NSString* newStr = [[NSString alloc]initWithData:dec encoding:NSUTF8StringEncoding];
    NSLog(@"dec is %@",newStr);

Ill get a hex string which is a json after decrypting i am unable to parse it as it returns null. How to achieve that any help

**Comment by michaelnwanna** [comment]
Hi Gantios, there is probably an exception inside the method "decryptedDataFromData". Step into the method and see whats going on.

Cheers//

**Comment by Gantaios** [comment]
Hi michaelnwanna, when i print data i can see the data it gets printed but when i try to convert it does not convert can you help me

i am gettig a hexString i need to decrypt and parse it its a json

**Comment by Gantaios** [comment]
my key and iv looks like this 
    NSString *iv = @"0q1z2a3a4p5a6789";
    NSString *key = @"9876a5p4a3a2z1q0";
and response from server is "5ca9b162fe2936c0fd7f5a834d3d874a8ae39a5d482509a82b50e8ea5248cc2ce8acce5ae4c6ac1677918ffea9e3454b894fd06d1a0baae59384aa456b3eb90b"

need to decrypt it and parse in android they achieved the same i am unable to any help

**Comment by michaelnwanna** [comment]
I also got NULL while trying to decrypt the server response.  You need to look at your encryption again. Did you encrypt with same iv & key?

Cheers//

**Comment by Gantaios** [comment]
Hi michaelwanna yes am using the same key and iv in android they are able able to decrypt the data successfully but in my case it's not happening am new to this topic can you help me. Is there something which i need to ask the PHP guy

**Comment by michaelnwanna** [comment]
Hi.
Try encrypting and decryting with BBAES on IOS and share your findings.
You may also try decrypting the encryted data on Android.
You are likely going to see where the mix is coming from with this simple task.

Cheers//

**Comment by Gantaios** [comment]
ok ill try and ill come up Thanks
